import logging
from typing import Dict, Any, List, Optional

logger = logging.getLogger("stage.notification_templates")

# ─── SUBJECT LINE TEMPLATES ──────────────────────────────────────────────────

BLUEPRINT_SUBJECTS = {
    "comment_created": lambda m: f"[STAGE] {m.get('author_name', 'A teammate')} commented on '{m.get('target_selector', 'canvas element')}'",
    "comment_resolved": lambda m: f"[STAGE] Comment resolved on '{m.get('target_selector', 'canvas element')}'",
    "comment_reopened": lambda m: f"[STAGE] Comment reopened on '{m.get('target_selector', 'canvas element')}'",
    "publication_created": lambda m: f"[STAGE] Release v{m.get('version', '1')} draft published for {m.get('project_name', 'project')}",
    "publication_status_changed": lambda m: f"[STAGE] Release v{m.get('version', '1')} is now {m.get('status', 'updated').upper()}",
    "edit_created": lambda m: f"[STAGE] {m.get('edit_count', 1)} new Blueprint edit(s) saved",
    "summary_generated": lambda m: f"[STAGE] AI change summary generated for {m.get('project_name', 'project')}"
}

SESSION_SUBJECTS = {
    "marker_created": lambda m: f"[STAGE Session] New pin added on '{m.get('target_selector', 'page element')}'",
    "marker_resolved": lambda m: f"[STAGE Session] Pin resolved on '{m.get('target_selector', 'page element')}'",
    "session_started": lambda m: f"[STAGE Session] Review session started: {m.get('session_title', 'Audit Session')}",
    "session_closed": lambda m: f"[STAGE Session] Review session closed for {m.get('project_name', 'project')}",
    "export_created": lambda m: f"[STAGE Session] CSS/JSON export package generated",
    "share_link_created": lambda m: f"[STAGE Session] Share link generated for client review"
}


def build_notification_subject(
    source_type: str,
    event_type: str,
    metadata: Optional[Dict[str, Any]] = None,
    tone: str = "client_friendly"
) -> str:
    meta = metadata or {}
    if source_type == "blueprint" and event_type in BLUEPRINT_SUBJECTS:
        subj = BLUEPRINT_SUBJECTS[event_type](meta)
    elif source_type == "session" and event_type in SESSION_SUBJECTS:
        subj = SESSION_SUBJECTS[event_type](meta)
    else:
        proj = meta.get("project_name", "STAGE Project")
        subj = f"[STAGE] {event_type.replace('_', ' ').title()} in {proj}"

    if tone == "concise":
        subj = subj.replace("[STAGE Session]", "[STAGE]").replace(" generated", "").replace(" published", "")
    elif tone == "developer":
        subj = f"[STAGE Dev] {event_type}: {meta.get('target_selector', meta.get('session_title', 'event'))}"

    return subj


def build_notification_body(
    source_type: str,
    event_type: str,
    metadata: Optional[Dict[str, Any]] = None,
    tone: str = "client_friendly"
) -> str:
    meta = metadata or {}
    actor = meta.get("author_name", meta.get("actor_name", "A collaborator"))
    target = meta.get("target_selector", "the canvas")
    proj = meta.get("project_name", "your STAGE workspace")

    if source_type == "blueprint":
        if event_type == "comment_created":
            body = f"{actor} posted feedback on '{target}' in project '{proj}': \"{meta.get('comment_snippet', meta.get('body', 'New comment.'))}\""
        elif event_type == "publication_status_changed":
            body = f"Release v{meta.get('version', '1')} status was updated to '{meta.get('status', 'in_review').replace('_', ' ').title()}' by {actor}."
        elif event_type == "publication_created":
            body = f"{actor} created publication release v{meta.get('version', '1')} with {meta.get('edit_count', 0)} edit(s) for client review."
        else:
            body = f"{actor} performed '{event_type.replace('_', ' ')}' on {target}."
    else: # session
        if event_type == "marker_created":
            body = f"{actor} placed a review pin on '{target}' during session '{meta.get('session_title', 'Session')}': \"{meta.get('comment_snippet', 'New pin.')}\""
        elif event_type == "session_started":
            body = f"{actor} initiated a developer review session '{meta.get('session_title', 'Audit Session')}' for {proj}."
        elif event_type == "export_created":
            body = f"A production-ready CSS/JSON export package was generated by {actor}."
        else:
            body = f"{actor} performed '{event_type.replace('_', ' ')}' in session."

    if tone == "concise":
        body = body.split(". ")[0] + "."
    elif tone == "developer":
        body += f" [Entity: {meta.get('entity_id', 'N/A')}]"

    return body


def build_preview_text(
    source_type: str,
    event_type: str,
    metadata: Optional[Dict[str, Any]] = None
) -> str:
    meta = metadata or {}
    actor = meta.get("author_name", meta.get("actor_name", "A teammate"))
    if source_type == "blueprint":
        return f"{actor} updated Blueprint Canvas: {event_type.replace('_', ' ')}"
    else:
        return f"{actor} updated Session Review: {event_type.replace('_', ' ')}"


def build_why_you_got_this(
    source_type: str,
    event_type: str,
    category: str = "important"
) -> str:
    if source_type == "blueprint":
        return f"You're receiving this because email alerts are enabled for STAGE Blueprint {event_type.replace('_', ' ')} events."
    else:
        return f"You're receiving this because email alerts are enabled for STAGE Session Review activity."
