[phases.setup]
nixPkgs = [
    "...",
    "glib",
    "nss",
    "nspr",
    "atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "mesa",
    "alsa-lib",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXrandr",
    "pango",
    "cairo"
]
