"""add_canonical_user_fields

Revision ID: 8b24c4b21291
Revises: fb605e50789d
Create Date: 2026-08-03 18:06:18.432719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b24c4b21291'
down_revision: Union[str, Sequence[str], None] = 'fb605e50789d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_canvas_flows_project_id'), 'canvas_flows', ['project_id'], unique=False)
    op.create_index(op.f('ix_canvas_frames_project_id'), 'canvas_frames', ['project_id'], unique=False)
    op.create_index(op.f('ix_canvas_frames_session_id'), 'canvas_frames', ['session_id'], unique=False)
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_index(op.f('ix_org_invites_created_by'), 'org_invites', ['created_by'], unique=False)
    op.create_index(op.f('ix_org_invites_org_id'), 'org_invites', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_members_org_id'), 'org_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_members_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_index(op.f('ix_sessions_project_id'), 'sessions', ['project_id'], unique=False)
    op.add_column('user_identities', sa.Column('email_verified', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_identities', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('onboarding_state_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferences_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences_json')
    op.drop_column('users', 'onboarding_state_json')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('user_identities', 'updated_at')
    op.drop_column('user_identities', 'email_verified')
    op.drop_index(op.f('ix_sessions_project_id'), table_name='sessions')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_index(op.f('ix_org_members_user_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_org_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_invites_org_id'), table_name='org_invites')
    op.drop_index(op.f('ix_org_invites_created_by'), table_name='org_invites')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_index(op.f('ix_canvas_frames_session_id'), table_name='canvas_frames')
    op.drop_index(op.f('ix_canvas_frames_project_id'), table_name='canvas_frames')
    op.drop_index(op.f('ix_canvas_flows_project_id'), table_name='canvas_flows')
    # ### end Alembic commands ###
