"""add_markers_v2

Revision ID: aa1d8e603fda
Revises: fa504e40678c
Create Date: 2026-07-02 12:47:55.680960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1d8e603fda'
down_revision: Union[str, Sequence[str], None] = 'fa504e40678c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'markers_v2',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.String(), nullable=False),
        sa.Column('creator_id', sa.String(), nullable=True),
        sa.Column('creator_name', sa.String(), nullable=True),
        sa.Column('creator_role', sa.String(), nullable=True),
        sa.Column('x', sa.Float(), nullable=False),
        sa.Column('y', sa.Float(), nullable=False),
        sa.Column('page_url', sa.String(), nullable=True),
        sa.Column('note', sa.Text(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='open'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markers_v2_session_id'), 'markers_v2', ['session_id'], unique=False)
    op.create_index(op.f('ix_markers_v2_creator_id'), 'markers_v2', ['creator_id'], unique=False)
    op.create_index(op.f('ix_markers_v2_created_at'), 'markers_v2', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markers_v2_created_at'), table_name='markers_v2')
    op.drop_index(op.f('ix_markers_v2_creator_id'), table_name='markers_v2')
    op.drop_index(op.f('ix_markers_v2_session_id'), table_name='markers_v2')
    op.drop_table('markers_v2')
    # ### end Alembic commands ###
