"""create_markers_and_reviewers

Revision ID: b3e00cae3bfb
Revises: aa1d8e603fda
Create Date: 2026-07-02 15:15:12.958673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3e00cae3bfb'
down_revision: Union[str, Sequence[str], None] = 'aa1d8e603fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='reviewer', nullable=False),
    sa.Column('color_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_identities_created_at'), 'reviewer_identities', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviewer_identities_session_id'), 'reviewer_identities', ['session_id'], unique=False)
    op.drop_index(op.f('ix_markers_v2_created_at'), table_name='markers_v2')
    op.drop_index(op.f('ix_markers_v2_creator_id'), table_name='markers_v2')
    op.drop_index(op.f('ix_markers_v2_session_id'), table_name='markers_v2')
    op.drop_table('markers_v2')
    op.add_column('markers', sa.Column('creator_id', sa.String(), nullable=True))
    op.add_column('markers', sa.Column('creator_name', sa.String(), nullable=True))
    op.add_column('markers', sa.Column('creator_role', sa.String(), nullable=True))
    op.add_column('markers', sa.Column('color_token', sa.String(), nullable=True))
    op.add_column('markers', sa.Column('anchor_kind', sa.String(), nullable=False))
    op.add_column('markers', sa.Column('target_selector', sa.String(), nullable=True))
    op.add_column('markers', sa.Column('target_xpath', sa.String(), nullable=True))
    op.add_column('markers', sa.Column('dom_text_excerpt', sa.Text(), nullable=True))
    op.add_column('markers', sa.Column('offset_x_ratio', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('offset_y_ratio', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('page_x', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('page_y', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('viewport_width', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('viewport_height', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('element_rect_json', sa.JSON(), nullable=True))
    op.add_column('markers', sa.Column('scroll_x', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('scroll_y', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('canvas_id', sa.String(), nullable=True))
    op.add_column('markers', sa.Column('canvas_x_ratio', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('canvas_y_ratio', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('webgl_clip_x', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('webgl_clip_y', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('markers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('markers', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('markers', sa.Column('device_pixel_ratio', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('console_errors_json', sa.JSON(), nullable=True))
    op.add_column('markers', sa.Column('network_errors_json', sa.JSON(), nullable=True))
    op.add_column('markers', sa.Column('encrypted_context', sa.String(), nullable=True))
    op.alter_column('markers', 'project_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('markers', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('markers', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('markers', 'priority',
               existing_type=postgresql.ENUM('critical', 'high', 'medium', 'low', name='priorityenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_markers_page_visit_id'), table_name='markers')
    op.drop_index(op.f('ix_markers_share_link_id'), table_name='markers')
    op.drop_index(op.f('ix_markers_user_id'), table_name='markers')
    op.drop_constraint(op.f('uq_session_marker_number'), 'markers', type_='unique')
    op.create_index(op.f('ix_markers_creator_id'), 'markers', ['creator_id'], unique=False)
    op.create_index(op.f('ix_markers_project_id'), 'markers', ['project_id'], unique=False)
    op.create_index(op.f('ix_markers_status'), 'markers', ['status'], unique=False)
    op.drop_constraint(op.f('markers_session_id_fkey'), 'markers', type_='foreignkey')
    op.drop_constraint(op.f('markers_share_link_id_fkey'), 'markers', type_='foreignkey')
    op.drop_constraint(op.f('markers_assignee_id_fkey'), 'markers', type_='foreignkey')
    op.drop_constraint(op.f('markers_user_id_fkey'), 'markers', type_='foreignkey')
    op.create_foreign_key(None, 'markers', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'markers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('markers', 'inner_text')
    op.drop_column('markers', 'parent_page_id')
    op.drop_column('markers', 'url')
    op.drop_column('markers', 'aria_label')
    op.drop_column('markers', 'element_text')
    op.drop_column('markers', 'y')
    op.drop_column('markers', 'share_link_id')
    op.drop_column('markers', 'user_id')
    op.drop_column('markers', 'screenshots')
    op.drop_column('markers', 'coordinates')
    op.drop_column('markers', 'shadow_host_class_list')
    op.drop_column('markers', 'source')
    op.drop_column('markers', 'marker_number')
    op.drop_column('markers', 'ai_summary')
    op.drop_column('markers', 'scroll_position')
    op.drop_column('markers', 'created_via')
    op.drop_column('markers', 'canvas_context')
    op.drop_column('markers', 'aria_role')
    op.drop_column('markers', 'css_selector')
    op.drop_column('markers', 'assignee_id')
    op.drop_column('markers', 'note')
    op.drop_column('markers', 'is_inside_shadow_dom')
    op.drop_column('markers', 'bounding_box')
    op.drop_column('markers', 'norm_y')
    op.drop_column('markers', 'shadow_host_id')
    op.drop_column('markers', 'element_selector')
    op.drop_column('markers', 'created_by')
    op.drop_column('markers', 'severity')
    op.drop_column('markers', 'x')
    op.drop_column('markers', 'browser_info')
    op.drop_column('markers', 'shadow_path')
    op.drop_column('markers', 'comment')
    op.drop_column('markers', 'canvas_snapshot')
    op.drop_column('markers', 'diagnostics')
    op.drop_column('markers', 'shadow_host_tag')
    op.drop_column('markers', 'target')
    op.drop_column('markers', 'screenshot_required')
    op.drop_column('markers', 'capture_payload')
    op.drop_column('markers', 'issue_type')
    op.drop_column('markers', 'console_errors')
    op.drop_column('markers', 'shadow_root_depth')
    op.drop_column('markers', 'xpath')
    op.drop_column('markers', 'element_tag')
    op.drop_column('markers', 'norm_x')
    op.drop_column('markers', 'viewport')
    op.drop_column('markers', 'network_errors')
    op.drop_column('markers', 'agent_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('agent_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('network_errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('viewport', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('norm_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('element_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('xpath', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('shadow_root_depth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('console_errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('issue_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('capture_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('screenshot_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('target', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('shadow_host_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('diagnostics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('canvas_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('shadow_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('browser_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('element_selector', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('shadow_host_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('norm_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('bounding_box', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('is_inside_shadow_dom', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('assignee_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('css_selector', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('aria_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('canvas_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('created_via', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('scroll_position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('marker_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('source', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('shadow_host_class_list', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('screenshots', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('share_link_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('element_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('aria_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('parent_page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('inner_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'markers', type_='foreignkey')
    op.drop_constraint(None, 'markers', type_='foreignkey')
    op.create_foreign_key(op.f('markers_user_id_fkey'), 'markers', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('markers_assignee_id_fkey'), 'markers', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key(op.f('markers_share_link_id_fkey'), 'markers', 'share_links', ['share_link_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('markers_session_id_fkey'), 'markers', 'sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_markers_status'), table_name='markers')
    op.drop_index(op.f('ix_markers_project_id'), table_name='markers')
    op.drop_index(op.f('ix_markers_creator_id'), table_name='markers')
    op.create_unique_constraint(op.f('uq_session_marker_number'), 'markers', ['session_id', 'marker_number'])
    op.create_index(op.f('ix_markers_user_id'), 'markers', ['user_id'], unique=False)
    op.create_index(op.f('ix_markers_share_link_id'), 'markers', ['share_link_id'], unique=False)
    op.create_index(op.f('ix_markers_page_visit_id'), 'markers', ['page_visit_id'], unique=False)
    op.alter_column('markers', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('critical', 'high', 'medium', 'low', name='priorityenum'),
               existing_nullable=False)
    op.alter_column('markers', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('markers', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('markers', 'project_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('markers', 'encrypted_context')
    op.drop_column('markers', 'network_errors_json')
    op.drop_column('markers', 'console_errors_json')
    op.drop_column('markers', 'device_pixel_ratio')
    op.drop_column('markers', 'version')
    op.drop_column('markers', 'deleted_at')
    op.drop_column('markers', 'is_deleted')
    op.drop_column('markers', 'webgl_clip_y')
    op.drop_column('markers', 'webgl_clip_x')
    op.drop_column('markers', 'canvas_y_ratio')
    op.drop_column('markers', 'canvas_x_ratio')
    op.drop_column('markers', 'canvas_id')
    op.drop_column('markers', 'scroll_y')
    op.drop_column('markers', 'scroll_x')
    op.drop_column('markers', 'element_rect_json')
    op.drop_column('markers', 'viewport_height')
    op.drop_column('markers', 'viewport_width')
    op.drop_column('markers', 'page_y')
    op.drop_column('markers', 'page_x')
    op.drop_column('markers', 'offset_y_ratio')
    op.drop_column('markers', 'offset_x_ratio')
    op.drop_column('markers', 'dom_text_excerpt')
    op.drop_column('markers', 'target_xpath')
    op.drop_column('markers', 'target_selector')
    op.drop_column('markers', 'anchor_kind')
    op.drop_column('markers', 'color_token')
    op.drop_column('markers', 'creator_role')
    op.drop_column('markers', 'creator_name')
    op.drop_column('markers', 'creator_id')
    op.create_table('markers_v2',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creator_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creator_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('page_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('markers_v2_creator_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('markers_v2_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('markers_v2_pkey'))
    )
    op.create_index(op.f('ix_markers_v2_session_id'), 'markers_v2', ['session_id'], unique=False)
    op.create_index(op.f('ix_markers_v2_creator_id'), 'markers_v2', ['creator_id'], unique=False)
    op.create_index(op.f('ix_markers_v2_created_at'), 'markers_v2', ['created_at'], unique=False)
    op.drop_index(op.f('ix_reviewer_identities_session_id'), table_name='reviewer_identities')
    op.drop_index(op.f('ix_reviewer_identities_created_at'), table_name='reviewer_identities')
    op.drop_table('reviewer_identities')
    # ### end Alembic commands ###
