"""Init Schema Sync

Revision ID: fa504e40678c
Revises: 
Create Date: 2026-07-01 17:12:04.880152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa504e40678c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('markers', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('markers', 'capture_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('markers', 'coordinates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('markers', 'target',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('markers', 'source',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('markers', 'screenshots',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('markers', 'diagnostics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('markers', 'client_x')
    op.drop_column('markers', 'viewport_height')
    op.drop_column('markers', 'client_y')
    op.drop_column('markers', 'review_token')
    op.drop_column('markers', 'deleted_at')
    op.drop_column('markers', 'reviewer_name')
    op.drop_column('markers', 'client_color')
    op.drop_column('markers', 'color_index')
    op.drop_column('markers', 'color_token')
    op.drop_column('markers', 'height')
    op.drop_column('markers', 'source_type')
    op.drop_column('markers', 'reviewer_id')
    op.drop_column('markers', 'width')
    op.drop_column('markers', 'viewport_width')
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.add_column('markers', sa.Column('viewport_width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('reviewer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('source_type', sa.VARCHAR(length=50), server_default=sa.text("'developer'::character varying"), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('color_token', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('color_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('client_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('reviewer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('review_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('client_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('viewport_height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('client_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('markers', 'diagnostics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('markers', 'screenshots',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('markers', 'source',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('markers', 'target',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('markers', 'coordinates',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('markers', 'capture_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('markers', 'status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
