'use client'

import React, { useState } from 'react'
import {
  Sparkles,
  X,
  Copy,
  Check,
  RefreshCw,
  AlertTriangle,
  CheckCircle2,
  FileText,
  ListChecks,
  ArrowRight
} from 'lucide-react'
import { useBlueprintSummaryStore, SummaryTone } from '@/store/blueprintSummaryStore'

interface BlueprintSummaryModalProps {
  projectId: string
  onClose: () => void
}

export function BlueprintSummaryModal({ projectId, onClose }: BlueprintSummaryModalProps) {
  const {
    activeSummary,
    isGenerating,
    generationError,
    currentTone,
    setCurrentTone,
    generateSummary
  } = useBlueprintSummaryStore()

  const [copied, setCopied] = useState(false)

  const handleCopyMarkdown = () => {
    if (!activeSummary) return

    const markdown = `
# ${activeSummary.title}
*Generated by STAGE AI Summarizer on ${new Date(activeSummary.created_at).toLocaleString()}*

## Executive Summary
${activeSummary.summary_text}

${activeSummary.bullets_json && activeSummary.bullets_json.length > 0 ? `## Key Changes Overview\n${activeSummary.bullets_json.map(b => `- ${b}`).join('\n')}\n` : ''}
${activeSummary.risks_json && activeSummary.risks_json.length > 0 ? `## Potential Considerations & Risks\n${activeSummary.risks_json.map(r => `- ⚠️ ${r}`).join('\n')}\n` : ''}
${activeSummary.followups_json && activeSummary.followups_json.length > 0 ? `## Recommended Next Steps\n${activeSummary.followups_json.map(f => `- ➡️ ${f}`).join('\n')}\n` : ''}
`.trim()

    navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleRegenerate = (tone: SummaryTone) => {
    setCurrentTone(tone)
    generateSummary(projectId, {
      publicationId: activeSummary?.blueprint_publication_id,
      tone: tone
    })
  }

  const tones: { id: SummaryTone; label: string; desc: string }[] = [
    { id: 'client_friendly', label: 'Client Friendly', desc: 'Clear, collaborative update' },
    { id: 'concise', label: 'Concise', desc: 'Short executive summary' },
    { id: 'detailed', label: 'Developer Detailed', desc: 'Technical & component breakdown' }
  ]

  return (
    <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-md flex items-center justify-center p-4 select-none animate-in fade-in duration-200">
      <div className="bg-[#090d16] border border-slate-800 rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/80">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-purple-500/10 border border-purple-500/30 flex items-center justify-center text-purple-400">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <span>STAGE AI Change Summary</span>
                <span className="px-2 py-0.5 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-[10px] font-mono font-extrabold uppercase">
                  AI Generated
                </span>
              </h3>
              <p className="text-xs text-slate-400">Client & Stakeholder Handoff Digest</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Tone Selector Tabs */}
        <div className="p-3 bg-slate-950/60 border-b border-slate-800 flex items-center justify-between gap-2 overflow-x-auto">
          <div className="flex items-center gap-1.5">
            <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mr-1">Tone:</span>
            {tones.map((t) => (
              <button
                key={t.id}
                onClick={() => handleRegenerate(t.id)}
                disabled={isGenerating}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                  currentTone === t.id
                    ? 'bg-purple-600 text-white shadow-md shadow-purple-600/20'
                    : 'bg-slate-900 text-slate-400 hover:bg-slate-800 hover:text-slate-200'
                }`}
                title={t.desc}
              >
                {t.label}
              </button>
            ))}
          </div>

          <button
            onClick={() => handleRegenerate(currentTone)}
            disabled={isGenerating}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-300 text-xs font-bold transition-colors cursor-pointer disabled:opacity-50"
            title="Regenerate Summary"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin text-purple-400' : ''}`} />
            <span>Regenerate</span>
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {isGenerating ? (
            <div className="flex flex-col items-center justify-center py-16 text-center space-y-3">
              <div className="relative">
                <div className="w-12 h-12 rounded-2xl bg-purple-500/10 border border-purple-500/30 flex items-center justify-center text-purple-400">
                  <Sparkles className="w-6 h-6 animate-pulse" />
                </div>
                <div className="absolute -inset-1 rounded-2xl border border-purple-500/40 animate-ping opacity-30" />
              </div>
              <p className="text-sm font-bold text-white">Synthesizing Blueprint Changes...</p>
              <p className="text-xs text-slate-400 max-w-xs">
                Analysing saved DOM mutations, publication status history, and feedback comments.
              </p>
            </div>
          ) : generationError ? (
            <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-rose-400 flex-shrink-0 mt-0.5" />
              <div>
                <h4 className="text-xs font-bold text-rose-300">Summary Generation Warning</h4>
                <p className="text-xs text-rose-400/90 mt-0.5">{generationError}</p>
              </div>
            </div>
          ) : activeSummary ? (
            <>
              {/* Title & Metadata Banner */}
              <div className="p-3.5 rounded-xl bg-slate-900/80 border border-slate-800 flex items-center justify-between">
                <div>
                  <h4 className="text-xs font-extrabold text-white tracking-wide">{activeSummary.title}</h4>
                  <p className="text-[10px] text-slate-400 mt-0.5 flex items-center gap-2">
                    <span>Model: {activeSummary.model_name}</span>
                    <span>•</span>
                    <span>{new Date(activeSummary.created_at).toLocaleString()}</span>
                  </p>
                </div>
              </div>

              {/* Executive Summary Paragraph */}
              <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/80 space-y-1.5">
                <h4 className="text-xs font-extrabold text-purple-400 uppercase tracking-wider flex items-center gap-1.5">
                  <FileText className="w-3.5 h-3.5" />
                  <span>Executive Overview</span>
                </h4>
                <p className="text-xs text-slate-200 leading-relaxed font-sans">
                  {activeSummary.summary_text}
                </p>
              </div>

              {/* Key Changes Bullets */}
              {activeSummary.bullets_json && activeSummary.bullets_json.length > 0 && (
                <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/80 space-y-2">
                  <h4 className="text-xs font-extrabold text-cyan-400 uppercase tracking-wider flex items-center gap-1.5">
                    <ListChecks className="w-3.5 h-3.5" />
                    <span>Key Modifications</span>
                  </h4>
                  <ul className="space-y-1.5">
                    {activeSummary.bullets_json.map((b, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0 mt-0.5" />
                        <span>{b}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Risks & Considerations */}
              {activeSummary.risks_json && activeSummary.risks_json.length > 0 && (
                <div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/20 space-y-2">
                  <h4 className="text-xs font-extrabold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    <span>Feedback & Approval Notes</span>
                  </h4>
                  <ul className="space-y-1.5">
                    {activeSummary.risks_json.map((r, idx) => (
                      <li key={idx} className="text-xs text-amber-300/90 flex items-start gap-2">
                        <span className="text-amber-400 font-bold">•</span>
                        <span>{r}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Followups & Next Steps */}
              {activeSummary.followups_json && activeSummary.followups_json.length > 0 && (
                <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/80 space-y-2">
                  <h4 className="text-xs font-extrabold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
                    <ArrowRight className="w-3.5 h-3.5" />
                    <span>Recommended Next Steps</span>
                  </h4>
                  <ul className="space-y-1.5">
                    {activeSummary.followups_json.map((f, idx) => (
                      <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                        <span className="text-emerald-400 font-bold">→</span>
                        <span>{f}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          ) : (
            <div className="py-12 text-center text-xs text-slate-400">
              No summary available. Click "Regenerate" to generate a STAGE AI Change Summary.
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="p-3.5 border-t border-slate-800 bg-slate-900/80 flex items-center justify-between">
          <button
            onClick={handleCopyMarkdown}
            disabled={!activeSummary || isGenerating}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold transition-all cursor-pointer disabled:opacity-50 shadow-md"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span className="text-emerald-400">Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>Copy as Markdown</span>
              </>
            )}
          </button>

          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs font-bold transition-all cursor-pointer shadow-lg shadow-cyan-500/20"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  )
}
